---
title: "Data exploration"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

# Loading data



```{r ilposdata}

load("../data/ilposdata.RData")
# load("../data/ilposdata.Rdata")

load("../data/paavodata.RData")
```

# table 1 
```{r}


#table 1 
library(arsenal)

tab1 <- tableby(gender ~ Hb + age+ aborh + age.group + FirstEvent, data=ilposdata)
summary(tab1, text=T)
results="asis"

# remove p-values + missing values and make it look prettier
```


# Preprocessing

You can also embed plots, for example:
## Donation data

```{r pressure, echo=FALSE}
nb_donations_data <-
  ilposdata %>% 
    mutate(Year = year(dateonly)) %>% 
    filter(donat_phleb == "K") %>% 
    count(donor,Year, zip)
 
 summarised_donor_data <- 
  ilposdata %>% 
    mutate(Year = year(dateonly),
           Hb = ifelse(is.nan(Hb), NA, Hb)) %>% 
    group_by(donor, Year, zip) %>% 
    summarize(mean_hb=mean(Hb, na.rm = TRUE)) %>% 
   drop_na(mean_hb) %>% 
   full_join(nb_donations_data,
             by = c("donor", "zip","Year")) %>% 
   mutate(n = replace_na(n, 0))

```

## Paavo data
```{r}
preprocessed_paavo_data <- 
  paavodata %>% 
    dplyr::select(pono, vuosi, hr_mtu, hr_ktu,nimi) %>% 
    rename(zip = pono,
           Year= vuosi,
           medianincome= hr_mtu,
           averageincome= hr_ktu,
           Zipname= nimi)
```



```{r}
final_data <-
  left_join(summarised_donor_data,
            preprocessed_paavo_data,
            by = c("zip", "Year")) %>% 
  filter(Year > 2014)
```

# Preliminary plots

```{r}
final_data %>% 
  ggplot(aes(x = medianincome)) +
  geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )
```
```{r}
final_data %>% 
  ggplot(aes(x = averageincome)) +
  geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )
```
# educational, living arragements and job-status  distributions
```{r} 
#add educational data to paavodata and combine the education data to 3 categories: 1) basic level 2) Matriculation examination and vocational diploma, 3) university degree (higher and lower)

preprocessed_paavo_data <- 
  paavodata %>% 
    dplyr::select(pono, vuosi, hr_mtu, hr_ktu,nimi, ko_perus, ko_yliop, ko_ammat, ko_al_kork, ko_yl_kork, pt_tyott, pt_opisk, pt_tyoll, te_omis_as, te_vuok_as) %>% 
    rename(zip = pono,
           Year= vuosi,
           medianincome= hr_mtu,
           averageincome= hr_ktu,
           Zipname= nimi,
           Basiceducation=ko_perus,
           unemployed = pt_tyott,
           students = pt_opisk,
           employed = pt_tyoll,
           owner_apartment = te_omis_as,
           rental_apartment = te_vuok_as)

#Remove the old variables, which were combined
preprocessed_paavo_data["secondaryeducation"] <- rowSums(preprocessed_paavo_data[c("ko_yliop",
                                  "ko_ammat")])
preprocessed_paavo_data["tertiaryeducation"] <- rowSums(preprocessed_paavo_data[c("ko_al_kork",
                                 "ko_yl_kork")])

preprocessed_paavo_data <- subset(preprocessed_paavo_data, select=-c(ko_yliop,
                                                                     ko_ammat,
                                                                     ko_al_kork,
                                                                     ko_yl_kork))


final_data <-
  left_join(final_data,
            preprocessed_paavo_data,
            by = c("zip", "Year")) %>% 
  filter(Year > 2014)
```


```{r} 
final_data %>% 
ggplot(aes(x = Basiceducation)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )
```
```{r}
final_data %>% 
ggplot(aes(x = secondaryeducation)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )

```

```{r}
final_data %>% 
ggplot(aes(x = tertiaryeducation)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )
```

# Plotting housing variables 
```{r}
final_data  %>% 
ggplot(aes(x = owner_apartment)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )

final_data  %>% 
ggplot(aes(x = rental_apartment)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )

```

# Plotting main type of activity 
```{r}
final_data  %>% 
ggplot(aes(x = unemployed)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )

final_data  %>% 
ggplot(aes(x = employed)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )

final_data  %>% 
ggplot(aes(x = students)) +
geom_histogram(binwidth = 1000) +
  facet_grid(Year ~. )


```

```
# Voter turnout and biggest party by zip-code (pending)
```{r}


```


```
#GGally correlation matrix 
```{r}
library("GGally")
```


#Summarise the data by hb + average yearly count of donations 

