---
title: "Helsinki-Uusimaa"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


load("/home/ilpo/Paavo/data/preprocessed.2019-07-24.RData")
setwd(dir="/home/ilpo/Paavo/src")
getwd()
```

```{r}
library(tidyverse)
library(viridis)
library(lubridate)
```



# Helsinki-Uusimaa is done by filtering zip smaller than 1. It only leaves 695 obs at the dataset. 
```{r}
huuma <-preprosessed_paavo %>% 
filter(zip < 1) 
str(huuma)

```

#Filtering out 0.00 values and places with less than 99 people. Also Otaniemi has been removed because big proportion of students and because of that lowest income in Uusimaa. 
```{r}
filter(eligible_population > 99) %>%
filter(prop_new_donors > 0.000) %>% 
filter(prop_repeat_donors > 0.00) 

```



```{r}


ggplot(data=huuma, mapping = aes(x= medianincome, y= prop_donors, color= eligible_population))+
geom_point(mapping = aes(x= medianincome, y= prop_donors)) +
geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") + 
facet_grid(Year~.)
```
```{r}
huuma <-preprosessed_paavo %>% 
filter(zip < 1) 

ggplot(data=huuma, mapping = aes(x= proportion_inhabitants_with_higher_education, y= prop_donors, color= eligible_population))+
geom_point(mapping = aes(x= proportion_inhabitants_with_higher_education, y= prop_donors)) +
geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") +
facet_grid(Year~.)
```
```{r}
ggplot(data=huuma, mapping = aes(x= medianincome, y= prop_donors, color= eligible_population))+
geom_point(mapping = aes(x= medianincome, y= prop_donors)) +
geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") + 
facet_grid(Year~.)
```



#new donors

```{r}
ggplot(data=huuma, mapping = aes(x= medianincome, y= prop_new_donors, color= eligible_population))+
geom_point(mapping = aes(x= medianincome, y= prop_new_donors)) +
geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") + 
facet_grid(Year~.)
```



#repeat donors

```{r}
ggplot(data=huuma, mapping = aes(x= medianincome, y= prop_repeat_donors, color= eligible_population))+
geom_point(mapping = aes(x= medianincome, y= prop_repeat_donors)) +
geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") + 
facet_grid(Year~.)
```


```{r}
ggplot(data=huuma, mapping = aes(x= medianincome, y= prop_donors, group= zip, color=eligible_population))+
geom_point(mapping = aes(x= medianincome, y= prop_donors)) +
#geom_smooth () + 
scale_x_log10() +
scale_color_viridis(discrete=FALSE,direction = -1,trans="log") + 
geom_boxplot() 
#coord_flip()
```

  # Not very informative part

```{r}
 ggplot(data = huuma,
            mapping = aes(x = medianincome, y = prop_donors))+
geom_point(alpha= 0.25) +
scale_x_log10() + 
  geom_text(data = huuma,check_overlap = TRUE, na.rm= TRUE, size=3,
mapping = aes(label = nimi)) + 
facet_grid(Year ~.)

```
```{r}
 ggplot(data = huuma,
            mapping = aes(x = proportion_inhabitants_with_higher_education, y = prop_donors))+
geom_point(alpha= 0.25) +
scale_x_log10() + 
  geom_text(data = huuma,check_overlap = TRUE,show.legend = TRUE,hjust = 0,
mapping = aes(label = nimi)) +
facet_grid(Year ~.)
```


```{r}
huuma %>% 
filter(eligible_population > 99 )
ggplot(data = huuma,
            mapping = aes(x = eligible_population, y = prop_donors))+
geom_point(alpha= 0.25) +
scale_x_log10() + 
 geom_smooth() +
facet_grid(Year ~.)

```

```{r}
ggplot(data=huuma, mapping = aes(x= eligible_population))+
geom_histogram (binwidth= 100) 
```

